package org.existdb.plugin

import org.gradle.api.GradleException
import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.api.tasks.Copy
import org.gradle.api.tasks.Delete
import org.gradle.api.tasks.bundling.Zip
import org.gradle.kotlin.dsl.*

public enum class PackageType(val typeName: String) {
    LIBRARY("library"),
    APPLICATION("application");

    override fun toString(): String = typeName
}

public data class VersionedDependency(val name: String, val version: String, val minVersion: String, val maxVersion: String)

public val exist640orLater = VersionedDependency("exist", "", "6.4.0", "")
public val exist6only = VersionedDependency("exist", "", "6", "6")
public val exist7orLater = VersionedDependency("exist", "", "7", "")

open class XarExtension {
    // XAR package metadata
    var namespace: String = ""
    var abbrev: String = ""
    var title: String = ""
    var description: String = ""
    var home: String = ""
    var status: String = ""
    var license: String = ""
    var target: String = ""
    var author: String = ""
    // the type of the package, e.g. "library", "application"
    var type: PackageType = PackageType.APPLICATION
    // the version of the package, which is taken from the project version
    var version: String = ""

    // optional scripts to be executed during installation, update, or removal of the package
    var prepare: String = ""
    var finish: String = ""
    var cleanup: String = ""

    // the main class that is generated by this project 
    var javaClass: String = ""
    // if export is true, the main class can be used by other packages
    var export: Boolean = true

    // dependencies are defined as tuples of (name, version, minVersion, maxVersion)
    // to allow for flexible version specifications in the generated expath-pkg.xml
    var requiredJars: List<String> = emptyList()
    var packageDependencies: List<VersionedDependency> = emptyList()
    var processorDependencies: List<VersionedDependency> = emptyList()
}

class XarPlugin : Plugin<Project> {
    override fun apply(project: Project) {
        val extension = project.extensions.create("xar", XarExtension::class.java)

        val buildDirProvider = project.layout.buildDirectory

        val validateXarExtension = project.tasks.register("validateXarExtension") {
            group = "verification"
            description = "Validates the XAR extension configuration"

            doLast {
                if (extension.javaClass.isEmpty()) {
                    throw GradleException("XAR plugin requires 'javaClass' to be set in the 'xar' extension")
                }
                if (extension.namespace.isEmpty()) {
                    throw GradleException("XAR plugin requires 'namespace' to be set in the 'xar' extension")
                }
                if (extension.type == PackageType.APPLICATION && extension.target.isEmpty()) {
                    throw GradleException("XAR plugin: 'target' must be set for application packages")
                }
            }
        }

        val createXarResources = project.tasks.register("createXarResources") {
            group = "prepare"
            description = "Creates the folder for XAR resources"
            outputs.dir(buildDirProvider.dir("xar-resources"))

            doLast {
                buildDirProvider.dir("xar-resources").get().asFile.mkdirs()
                buildDirProvider.dir("xar-resources/content").get().asFile.mkdirs()
            }
        }

        val copyXarResources = project.tasks.register<Copy>("copyXarResources") {
            group = "build"
            description = "Copies additional package contents to output directory for XAR packaging"
            dependsOn(createXarResources)
            from("src/main/xar-resources")
            into(buildDirProvider.dir("xar-resources"))
        }

        val cleanXarResources = project.tasks.register<Delete>("cleanXarResources") {
            group = "build"
            description = "Cleans the XAR resources directory"
            delete(buildDirProvider.dir("xar-resources"))
        }

        val createExpathPackageDescriptor = project.tasks.register("createExpathPackageDescriptor") {
            group = "build"
            description = "Creates the expath-pkg.xml descriptor for the XAR package"
            dependsOn(validateXarExtension, createXarResources)
            outputs.file(buildDirProvider.file("xar-resources/expath-pkg.xml"))

            doLast {
                val version = extension.version.ifEmpty { project.version.toString() }
                val abbrev = extension.abbrev.ifEmpty { project.name }
                val title = extension.title.ifEmpty { project.description ?: project.name }
                val home = extension.home.ifEmpty { project.findProperty("project.url") as? String ?: "" }

                val processorDependency = extension.processorDependencies.joinToString("\n") { (name, depVersion, minVersion, maxVersion) ->
                    val versionAttributes = listOfNotNull(
                        depVersion.takeIf { it.isNotEmpty() }?.let { """semver="$it"""" },
                        minVersion.takeIf { it.isNotEmpty() }?.let { """semver-min="$it"""" },
                        maxVersion.takeIf { it.isNotEmpty() }?.let { """semver-max="$it"""" }
                    ).joinToString(" ")
                    """<dependency processor="$name" $versionAttributes />"""
                }

                val packageDependencies = extension.packageDependencies.joinToString("\n") { (name, depVersion, minVersion, maxVersion) ->
                    val versionAttributes = listOfNotNull(
                        depVersion.takeIf { it.isNotEmpty() }?.let { """semver="$it"""" },
                        minVersion.takeIf { it.isNotEmpty() }?.let { """semver-min="$it"""" },
                        maxVersion.takeIf { it.isNotEmpty() }?.let { """semver-max="$it"""" }
                    ).joinToString(" ")
                    """<dependency package="$name" $versionAttributes />"""
                }

                buildDirProvider.file("xar-resources/expath-pkg.xml").get().asFile.writeText(
                    """<?xml version="1.0" encoding="UTF-8"?>
<package xmlns="http://expath.org/ns/pkg"
         xmlns:xs="http://www.w3.org/2001/XMLSchema"
         name="${extension.namespace}"
         abbrev="$abbrev"
         version="$version"
         spec="1.0">
   <title>$title</title>
   <home>$home</home>
   $processorDependency
   $packageDependencies
</package>"""
                )
            }
        }

        val createRepoXml = project.tasks.register("createRepoXml") {
            group = "build"
            description = "Creates the repo.xml descriptor for the XAR package"
            dependsOn(validateXarExtension, createXarResources)
            outputs.file(buildDirProvider.file("xar-resources/repo.xml"))

            doLast {
                val home = extension.home.ifEmpty { project.findProperty("project.url") as? String ?: "" }
                val scripts = listOfNotNull(
                    extension.prepare.takeIf { it.isNotEmpty() }?.let { """<prepare>$it</prepare>""" },
                    extension.finish.takeIf { it.isNotEmpty() }?.let { """<finish>$it</finish>""" },
                    extension.cleanup.takeIf { it.isNotEmpty() }?.let { """<cleanup>$it</cleanup>""" }
                ).joinToString("\n")

                val target = if (extension.target.isNotEmpty()) {
                    """<target>${extension.target}</target>"""
                } else ""

                buildDirProvider.file("xar-resources/repo.xml").get().asFile.writeText(
                    """<?xml version="1.0" encoding="UTF-8"?>
<meta xmlns="http://exist-db.org/xquery/repo"
      xmlns:repo="http://exist-db.org/xquery/repo"
      xmlns:xs="http://www.w3.org/2001/XMLSchema">
   <description>${extension.description}</description>
   <author>${extension.author}</author>
   <type>${extension.type}</type>
   $target
   <website>$home</website>
   <status>${extension.status}</status>
   <license>${extension.license}</license>
   <copyright>true</copyright>
   $scripts
</meta>"""
                )
            }
        }

        val createExistXml = project.tasks.register("createExistXml") {
            group = "build"
            description = "Creates exist.xml and copies required jars"
            dependsOn(validateXarExtension, createXarResources, "jar")
            outputs.file(buildDirProvider.file("xar-resources/exist.xml"))
            outputs.dir(buildDirProvider.dir("xar-resources/content"))

            doLast {
                val projectJarName = "${project.name}-${project.version}.jar"
                val allRequiredJars = (extension.requiredJars + projectJarName).distinct()

                val jarList = allRequiredJars.joinToString("\n") { "   <jar>$it</jar>" }

                val javaSection = if (extension.export) {
                    """   <java>
      <namespace>${extension.namespace}</namespace>
      <class>${extension.javaClass}</class>
   </java>"""
                } else ""

                buildDirProvider.file("xar-resources/exist.xml").get().asFile.writeText(
                    """<?xml version="1.0" encoding="UTF-8"?>
<package xmlns="http://exist-db.org/ns/expath-pkg"
         xmlns:xs="http://www.w3.org/2001/XMLSchema">
$javaSection
$jarList
</package>"""
                )

                val compiledJar = project.tasks.named("jar").get().outputs.files.singleFile
                val runtimeAndProjectJars = project.configurations.named("runtimeClasspath").get().files + compiledJar
                val selectedJarFiles = allRequiredJars.mapNotNull { name -> runtimeAndProjectJars.find { it.name == name } }

                if (selectedJarFiles.size != allRequiredJars.size) {
                    val missing = allRequiredJars - selectedJarFiles.map { it.name }
                    throw GradleException("Missing required JAR(s) for XAR: $missing")
                }

                selectedJarFiles.forEach { jarFile ->
                    project.copy {
                        from(jarFile)
                        into(buildDirProvider.dir("xar-resources/content"))
                    }
                }
            }
        }

        project.tasks.register<Zip>("makeXar") {
            group = "package"
            description = "Creates the XAR package for eXist-db"
            dependsOn(createXarResources, copyXarResources, createExpathPackageDescriptor, createRepoXml, createExistXml)

            from(buildDirProvider.dir("xar-resources")) {
                include("**/*")
            }

            archiveFileName.set("${project.name}-${project.version}.xar")
            destinationDirectory.set(buildDirProvider.dir("libs"))
        }

        project.tasks.named("build").configure {
            dependsOn("makeXar")
        }

        project.tasks.named("clean").configure {
            dependsOn(cleanXarResources)
        }
    }
}
