package org.existdb.plugin

import jdk.internal.agent.ConnectorAddressLink.export
import org.gradle.api.GradleException
import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.api.provider.ListProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Copy
import org.gradle.api.tasks.Delete
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.bundling.Zip
import org.gradle.kotlin.dsl.*

enum class PackageType(val typeName: String) {
    LIBRARY("library"),
    APPLICATION("application");

    override fun toString(): String = typeName
}

data class VersionedDependency(val name: String, val version: String, val minVersion: String, val maxVersion: String)

val exist640orLater = VersionedDependency("exist", "", "6.4.0", "")
val exist6only = VersionedDependency("exist", "", "6", "6")
val exist7orLater = VersionedDependency("exist", "", "7", "")

open class XarExtension {
    // XAR package metadata
    var namespace: String = ""
    var abbrev: String = ""
    var title: String = ""
    var description: String = ""
    var home: String = ""
    var status: String = ""
    var license: String = ""
    var target: String = ""
    var author: String = ""
    // the type of the package, e.g. "library", "application"
    var type: PackageType = PackageType.APPLICATION
    // the version of the package, which is taken from the project version
    var version: String = ""

    // optional scripts to be executed during installation, update, or removal of the package
    var prepare: String = ""
    var finish: String = ""
    var cleanup: String = ""

    // the main class that is generated by this project 
    var javaClass: String = ""
    // if export is true, the main class can be used by other packages
    var export: Boolean = true

    // dependencies are defined as tuples of (name, version, minVersion, maxVersion)
    // to allow for flexible version specifications in the generated expath-pkg.xml
    var requiredJars: List<String> = emptyList()
    var packageDependencies: List<VersionedDependency> = emptyList()
    var processorDependencies: List<VersionedDependency> = emptyList()
}

class XarPlugin : Plugin<Project> {
    override fun apply(project: Project) {
        val extension = project.extensions.create("xar", XarExtension::class.java)

        val buildDirProvider = project.layout.buildDirectory

        val validateXarExtension = project.tasks.register<ValidateXarExtensionTask>("validateXarExtension") {
            group = "verification"
            description = "Validates the XAR extension configuration"
            javaClass = extension.javaClass
            namespace = extension.namespace
            target = extension.target
            type = extension.type
        }

        val createXarResources = project.tasks.register("createXarResources") {
            group = "build"
            description = "Creates the folder for XAR resources"
            outputs.dir(buildDirProvider.dir("xar-resources"))

            doLast {
                buildDirProvider.dir("xar-resources").get().asFile.mkdirs()
                buildDirProvider.dir("xar-resources/content").get().asFile.mkdirs()
            }
        }

        val copyXarResources = project.tasks.register<Copy>("copyXarResources") {
            group = "build"
            description = "Copies additional package contents to output directory for XAR packaging"
            dependsOn(createXarResources)
            from("src/main/xar-resources")
            into(buildDirProvider.dir("xar-resources"))
        }

        val cleanXarResources = project.tasks.register<Delete>("cleanXarResources") {
            group = "build"
            description = "Cleans the XAR resources directory"
            delete(buildDirProvider.dir("xar-resources"))
        }

        val createExpathPackageDescriptor = project.tasks.register<CreateExpathPackageDescriptorTask>("createExpathPackageDescriptor") {
            group = "build"
            description = "Creates the expath-pkg.xml descriptor for the XAR package"
            dependsOn(validateXarExtension, createXarResources)

            javaClass = extension.javaClass
            namespace = extension.namespace
            target = extension.target
            version = extension.version
            title = extension.title
            home = extension.home
            abbrev = extension.abbrev

            processorDependencies = extension.processorDependencies
                .map { renderDependency(it, "processor") }
            packageDependencies = extension.packageDependencies
                .map { renderDependency(it, "package") }

            outputFile = buildDirProvider.file("xar-resources/expath-pkg.xml")
        }

        val createRepoXml = project.tasks.register<CreateRepoXmlTask>("createRepoXml") {
            group = "build"
            description = "Creates the repo.xml descriptor for the XAR package"
            dependsOn(validateXarExtension, createXarResources)

            home = extension.home
            prepare = extension.prepare
            finish = extension.finish
            cleanup = extension.cleanup
            pkgDesc = extension.description
            author = extension.author
            type = extension.type
            target = extension.target
            status = extension.status
            license = extension.license

            outputFile = buildDirProvider.file("xar-resources/repo.xml")
        }

        val createExistXml = project.tasks.register<CreateExistXmlTask>("createExistXml") {
            group = "build"
            description = "Creates exist.xml and copies required jars"
            dependsOn(validateXarExtension, createXarResources, "jar")
            javaClass = extension.javaClass
            namespace = extension.namespace
            export = extension.export
            requiredJars = extension.requiredJars

            runtimeClasspath.from(project.configurations.named("runtimeClasspath"))
            projectJar.from(project.tasks.named("jar"))

            contentDir = buildDirProvider.dir("xar-resources/content")
            outputFile = buildDirProvider.file("xar-resources/exist.xml")
        }

        val makeXar = project.tasks.register<Zip>("makeXar") {
            group = "build"
            description = "Creates the XAR package for eXist-db"
            dependsOn(createXarResources, copyXarResources, createExpathPackageDescriptor, createRepoXml, createExistXml)

            from(buildDirProvider.dir("xar-resources")) {
                include("**/*")
            }

            archiveFileName = "${project.name}-${project.version}.xar"
            destinationDirectory = buildDirProvider.dir("libs")
        }

        project.tasks.named("build").configure {
            dependsOn(makeXar)
        }

        project.tasks.named("clean").configure {
            dependsOn(cleanXarResources)
        }
    }
}
